python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
python cli.py j1 &
python cli.py j2 &
